### ISSUE TITLE
[functions.flattop] implement localization

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#14]
`Functions::FlatTop` is derived from `GlobalFunctionInterface` which is problematic, since the order is globally specified. We need to implement a proper `local_function()` where the order is determined for each entity: If the entity lies
* completely wihtin or completely without the transition reagion we can return 0,
* complete within the transition region we can return `3*dimDomain`
* lies inbetween we should return something larger than `3*dimDomain`.

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-functions#5
