### ISSUE TITLE
[functions.constant] move UnitMatrix

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#18]
see https://github.com/wwu-numerik/dune-stuff/commit/871dc86860ddf02a4883665fbd87c160f499d73a#commitcomment-7960134

**Comment by ftalbrecht** [comment]
Is anyone using `IdentityMatrix`, could you grep this in your code, @renemilk?

**Comment by renemilk** [comment]
Not me. Also dune-common has since gained an IdentityMatrix in dune-common/dune/common/identitymatrix.hh
