### ISSUE TITLE
[la.container] add matrix market support

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#28]
See http://math.nist.gov/MatrixMarket/. There is also some code available already: http://math.nist.gov/MatrixMarket/mmio-c.html

**Comment by renemilk** [comment]
https://github.com/blattms/dune-mm-amg

**Comment by ftalbrecht** [comment]
Very nice, this should provide a perfect start!

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-la#1
