### ISSUE TITLE
release-2.4

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#30]
Dear all,

I would like to prepare a release of dune-stuff in the following weeks. Some things we need to do or decide:

- [x] Are we compatible with the core modules, version 2.3.1? If yes, we should release a version 2.3.1 IMHO. If not, which version should we release, @renemilk?
- [ ] Do we build correctly for all combinations of modules present/missing?
- [x] Fix or close issues of the [next_release milestone](https://github.com/wwu-numerik/dune-stuff/milestones/next_release).
- [x] ~~Do we want to fix/include any issues of the [near_future milestone](https://github.com/wwu-numerik/dune-stuff/milestones/near_future), e.g. #16 or #14.~~
- [x] Do we want to fix/include any issues of the [far_future milestone](https://github.com/wwu-numerik/dune-stuff/milestones/far_future), e.g. #24.
- [x] Drop ```playground```.
- [ ] Add documentation where ever possible.
- [x] Update dependecies (and version) in ```dune.module```.
- [ ] tarballs

After the release I would like to drop everything that is deprecated.

**Comment by ftalbrecht** [comment]
`make headercheck test` succeeds for release and debug builds with `clang 3.5.1` and `gcc 4.9.2` with

* `dune-common`, `v2.3.1`
* `dune-fem`, some version
* `dune-geometry`, `v2.3.1`
* `dune-grid`, 'releases/2.3`
* `dune-istl`, `v2.3.1`
* `dune-localfunctions`, `v2.3.1`
* `dune-pdelab`, some version
* `dune-typetree`, `v2.3.1`

So all in all I think we can claim to be compatible to 2.3.1, so I propose to call the next release 2.1.3.

**Comment by renemilk** [comment]
You got a typo in the proposed version :P
I'm pro doing #18 and #23 from the [next_release milestone](https://github.com/wwu-numerik/dune-stuff/milestones/next_release).  Do not care about any from the near or far future milestones for the release

**Comment by ftalbrecht** [comment]
Ok, fixed the typo. Any thoughts on #23 or care to implement it? Somehow this looks like stuff you should do...

**Comment by renemilk** [comment]
Yeah, will do.

**Comment by ftalbrecht** [comment]
`+1`

**Comment by renemilk** [comment]
You probably want to test tarball generation and subsequent usage in full builds too btw.

**Comment by renemilk** [comment]
Is there a reason to not have the core modules on the 2.3.1 release tags in  the supermodule btw? We prolly want to reset those, at least until our 2.3.1 release, right?

**Comment by ftalbrecht** [comment]
I might have set the modules to the respective 2.3 release branches, but I agree we should just set them to the release tags. That is probably a bit cleaner, since this is what users will do...

**Comment by renemilk** [comment]
Since this announced release never happened and the core module 2.4 release is imminent (rc1 was out 1 week ago) I'm changing the title and respective tags.

**Comment by renemilk** [comment]
- next_release milestone is currently empty
- playground's empty
- explicitly mentioned issues in OP have been fixed

**Comment by renemilk** [comment]
Just as a reminder: core modules' rc-2 release was yesterday

**Comment by renemilk** [comment]
2.4 release happened on 2015-09-25

**Comment by renemilk** [comment]
Done
