### ISSUE TITLE
[grid.output.pgf] wrong use of functors

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#31]

**Comment by renemilk** [comment]
That's not super helpful as far as reports go.

**Comment by renemilk** [comment]
Sorry, forgot again what you told me in person. Leave a note please.

**Comment by ftalbrecht** [comment]
See pr #32, thats as much as I remember atm; I think entity and intersection functors were mixed. If either of us implements #36 it might be worth waiting, though.

**Comment by ftalbrecht** [comment]
Fixed by now, thanks to @renemilk.
