### ISSUE TITLE
[test.common_profiler] fails

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#34]
On my machine, debug build, clang 3.5.1:
    
    [ RUN      ] ProfilerTest.ScopedTiming
    /home/falbr_01/Projects/dune/dune-stuff-demos/dune-stuff/dune/stuff/test/common_profiler.cc:36: Failure
    Expected: (Dune::Stuff::Common::profiler().getTiming("ProfilerTest.ScopedTiming")) >= (long(dvalueRange.size() * wait_ms)), actual: 410 vs 426
    [  FAILED  ] ProfilerTest.ScopedTiming (451 ms)

release build, gcc 4.9.2:

    [ RUN      ] ProfilerTest.ScopedTiming
    /home/falbr_01/Projects/dune/dune-stuff-demos/dune-stuff/dune/stuff/test/common_profiler.cc:36: Failure
    Expected: (Dune::Stuff::Common::profiler().getTiming("ProfilerTest.ScopedTiming")) >= (long(dvalueRange.size() * wait_ms)), actual: 420 vs 426
    [  FAILED  ] ProfilerTest.ScopedTiming (450 ms)

This might be related to 68008b82b288074502888fe13c300f07d27fd443.

**Comment by renemilk** [comment]
Definetely not a regression. That test is fickle at best, you could just bump the confidence variable again. Iirc that's what I did the last time it started failing. All tests there rely on very correct busyWait imp, and afaict, there simply isn't one that's guaranteed to work on all platforms/compilers/etc.

**Comment by ftalbrecht** [comment]
K. Then perhaps we should use one that *usually* works on the buildbots. Is the test failing there?

**Comment by renemilk** [comment]
Buildbot's entirely red and purple atm, so no idea ;-)

**Comment by renemilk** [comment]
All's green currently, so I guess we're ok.
