### ISSUE TITLE
[functions] move to dune-gdt

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#35]

**Comment by renemilk** [comment]
Is there a net benefit to this other than your feeling of them "belonging" there?

**Comment by ftalbrecht** [comment]
Well, after the removal of the discrete function and dune-fem related stuff there is nothing left in dune stuff that makes use of those functions. With the EOL of dune-stuff possibly coming this year I am looking for where to place stuff. And since dune-gdt is the only place where those functions are used I thought to place them there. Another possible place would be the future `dune-grid-community`, but that does not exist yet...

**Comment by renemilk** [comment]
So wait and don't move twice?

**Comment by ftalbrecht** [comment]
Sounds reasonable, yup.

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-functions#4
