### ISSUE TITLE
drop unused

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#37]
There are several things that I would like to drop before the release or at least know if/why they are still needed, so please grep your code and see what is still in use:

* `common/loop_timer.hh`
* `common/math`
  - `colonProduct`
  - `dyadicProduct`
* `common/matrix`:
  - `MatrixDiagonal`
  - `matrixTrace`
  - `setMatrixDiag`
  - `areTransposed`
  - `addMatrix`
  - `writeSparseMatrix`
  - `readSparseMatrix`
  - `rowWiseMatrixMultiplication`
  - `printMemUsage`, `printMemUsageObject`
  - `forceTranspose`
* ~~`common/misc`~~:
  - ~~`wraparound_array` (move somewhere else?)~~
* `common/print`
  - `printFieldVector`
  - `printFieldMatrix`
  - `printSparseRowMatrixMatlabStyle`
  - `printISTLMatrixMatlabStyle`
  - `printDiscreteFunctionMatlabStyle` (should be useless or moved to gdt?)
  - `printDoubleVectorMatlabStyle`
  - `printDoubleVec`
  - `oneLinePrint`
  - `LocalMatrixPrintFunctor` (dune-fem related, drop?)
  - `LocalFunctionPrintFunctor` (s.a.)
  - `LocalFunctionVerbatimPrintFunctor` (s.a)
  - ~~`matrixToGnuplotStream`~~, ~~`matrixToGnuplotFile`~~ (use interfaces from LA?)
  - ~~`dimToAxisName`~~
* ~~`common/signals`~~
* ~~`common/tuple`~~
* `discretefunction/projection/heterogeneous`
* `fem/*`
* `grid/fakeentity`
* ~~`grid/structuredgridfactory`~~

**Comment by renemilk** [comment]
Definitely do not drop wraparound_array, signals, tuple, structuredgridfactory.
{colon,dyadic}Product is still used within stuff itself. I'd like to keep the matrix to gnuplot stuff, functionality wise, also dimToAxisName. Everything else id fair game for removal as far as I'm concerned.

**Comment by renemilk** [comment]
I've emptied heterogenous.hh in bfbbc136fec7fcf4d3990dcd7951747e1d05a880 feel free to actually remove the file whenever.

**Comment by ftalbrecht** [comment]
K, thx!

**Comment by renemilk** [comment]
Those commits should've removed everything you had marked in the previous series of commits.

**Comment by renemilk** [comment]
And that should be it with related changes methinks
