### ISSUE TITLE
Investigate adding optional ApplyOn argument to entity search

### ISSUE THREAD

**Issue by tobiasleibner** [wwu-numerik/dune-stuff#41]
For the PeriodicGridView, the periodic neighbor will always be on the boundary, so searching the whole GridView should be a waste of time. I tried adding an optional ApplyOn-Argument to the entity search and using EntityInLevelSearch(gridview, ApplyOn::BoundaryEntities) in the PeriodicGridView. This improved test_periodicview from 6000 ms to 3700 ms on my machine, but creating a PeriodicGridView with 300x300 Entities regressed from 30s to around 90s. Need to investigate where this difference comes from.

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-grid#5
