### ISSUE TITLE
ParameterTree interface change

### ISSUE THREAD

**Issue by renemilk** [wwu-numerik/dune-stuff#44]
Members subKeys and valueKeys got an "_" appended in dune-common in current master. We'll need some sort of delegating accessor functions in Configuration to stay compatible with both 2.3/4 core modules and the exadune repos.

**Comment by ftalbrecht** [comment]
Oh great! I just heard a talk yesterday by the founder of kitware how 9 percent of their budget goes into innovation and some 80 percent go into maintenance...

**Comment by renemilk** [comment]
I fixed this in 0f2db19b6a6dee5c1f6efcf4780575ee991a100c

**Comment by ftalbrecht** [comment]
Thx. Aren't they just lovely... :)
