### ISSUE TITLE
[grid.fakeentity] is needed by dune-pymor

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#47]
For one of the examples.

**Comment by renemilk** [comment]
Did you create this issue so we won;t remove the fake entity again?

**Comment by ftalbrecht** [comment]
Probably? :) I guess we should decide whether this stays here or is moved to dune-pymor...

**Comment by renemilk** [comment]
I can't think of a reason to keep it here then.

**Comment by ftalbrecht** [comment]
Me neither, I guess. Though one could use it to enable tests of functions without requiring a grid, or such things. But I do not see an immediate need for this...

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-grid#6
