### ISSUE TITLE
valid() of EigenRowMajorSparseMatrix not usable for complex matrices

### ISSUE THREAD

**Issue by BarbaraV** [wwu-numerik/dune-stuff#52]
This is due to the fact that the EigenMappedDenseVector is only implemented for entries of type double. The matrix-interface forwards the method valid() to the derived implementations, so that one cannot comment out valid() in EigenRowMajorSparseMatrix and use a (slower) method of the interface.

**Comment by ftalbrecht** [comment]
Ok, I thought valid was a virtual method. Since it is a CRTP method this should be fine the way it is, as long as no one calls valid() with complex entries. We will have to implement this in the future, though, as I suspect that you will need this once you start solving the linear system...

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-la#4
