### ISSUE TITLE
[la] add abstraction for eigenvalue computation

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#65]
We have had several occasions where we required the computation of eigenvalues and eigenvectors. I remember @tobiasleibner requiring them for finite volume fluxes in the context of dune-gdt and we require them for the `ESV2007::CutOff` function. Currently this only works when eigen is present. In the long run, it would be nice to have an abstraction for the computation of eigenvalues and eigen vectors, just as we have for the linear solvers

**Comment by renemilk** [comment]
Related: https://dune-project.org/flyspray/index.php?do=details&task_id=1705

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-la#3
