### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by renemilk** [wwu-numerik/dune-stuff#72]
I've already pruned some long-dead branches where I was sure.

**Comment by renemilk** [comment]
@ftalbrecht please have a look as well

**Comment by ftalbrecht** [comment]
* `issue-255`: not sure/don't care
* `RS2016`: current work, will be merged in due time
* `oberwolfach-2013-abstract-albrecht`: it has to be possible to `git checkout oberwolfach-...`, but it could be turned into a tag, if that helps
* `paamg_hack`: yours I guess?
* `pymor-paper-benchmarks`: should stay, at least for the time being
* `python-bindings`: I would like to keep this one for the pending pybindgen -> boost-python transition
* `testtools*` yours I guess

**Comment by renemilk** [comment]
One testtools is ongoing, the other one accidental :-D
I would prefer tags where its only a matter of conserving state with no ongoing work. Deleted issue-255 and paamg_hack now

**Comment by ftalbrecht** [comment]
Agreed! I hope I just converted `oberwolfach-2013-abstract-albrecht` to a tag^^ The only branch left for deletion is the `clang_format_applied` one, I guess...

**Comment by renemilk** [comment]
Which we'll do once #13  is cloes, yeah.
