### ISSUE TITLE
[grid.walker] rename `add`

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#73]
Turns out calling this method `add` was a terrible choice. There are matrix-based operators in dune-gdt which derive from grid walker. There, `add` should clearly add two matrix-based operators. There might be other places where this naming is not appropriate.
The method in question registers functors with the grid walker for local application. I would have liked to call it `register`, which is of course not possible. But something along those lines would be nice.

Any ideas?

**Comment by renemilk** [comment]
Maybe STL container like?

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-grid#1
