### ISSUE TITLE
do not require latex

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#74]
After a fresh install I could not configure dune-stuff without a latex compiler present. Though this does not happen too often, this dependency should in general be optional. I will just post some of the output here...
```
Could NOT find LATEX (missing:  LATEX_COMPILER) 
CMake Error at /home/falbr_01/Projects/dune/OS2015/dune-common/cmake/modules/UseLATEX.cmake:552 (MESSAGE):
  I need the latex command.
```

```
-- I could not find the pdflatex command.
CMake Error at /home/falbr_01/Projects/dune/OS2015/dune-common/cmake/modules/UseLATEX.cmake:552 (MESSAGE):
  I need the bibtex command.
```

```
CMake Error at /home/falbr_01/Projects/dune/OS2015/dune-common/cmake/modules/UseLATEX.cmake:552 (MESSAGE):
  I need the makeindex command.
```

```

**Comment by renemilk** [comment]
I hope you were not on current master when that happened: https://github.com/wwu-numerik/dune-stuff/commit/19c9bfe3e57d892b6bb11376f33ad33be182aa17
Otherwise please reopen.
