### ISSUE TITLE
[common.color] make use of background coloring

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#75]
We color strings for output in several places, usually without setting a background color. This may lead to hard to read terminal output, depending on the color scheme of the terminal.

We should thus consider to color the background, e.g., in the `TimedLogger`...

**Comment by renemilk** [comment]
There's no way of _getting_ the background color programmatically though, right?

**Comment by ftalbrecht** [comment]
Not that I know of, no.

I am not sure if there is a generic way of handling this problem at
all. But since I will have to adapt the `TimedLogger` at some point
(boost timer, for instance), I wanted to have a reminder to reconsider
the matter...

**Comment by renemilk** [comment]
Pretty sure the answer is "not really" or is at least depending on how broad your definition of "generic" is. See also https://stackoverflow.com/questions/2507337/is-there-a-way-to-determine-a-terminals-background-color

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-common#7
