### ISSUE TITLE
[functions] GlobalFunctionInterface does not compile for dimDomain != dimWorld

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#87]

**Comment by renemilk** [comment]
Could you please elaborate a little? Is a fix functionally impossible, ie the underlying grid doesn't support the embedding? Is it a matter of selecting the _right_ grids for the right tests?

**Comment by ftalbrecht** [comment]
Problem is: instantiating a grid provider compiles `visualize`, which requires a `BoundaryInfo` for the specified grid, which instantiates all boundary infos (forgot why). One of them, however, uses functions, which instantiates in particular `GlobalFunctionInterface` for the given grids an dimensions. This fails if `dimDomain != dimWorld`.

This could be the case since we extract the types from dune-fem's functions...

So in a way, this is a bug in `GlobalFunctionInterface`.

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-functions#3
