### ISSUE TITLE
Use linthub.io?

### ISSUE THREAD

**Issue by renemilk** [wwu-numerik/dune-stuff#94]
I did two tryout PRs here: https://github.com/renemilk/dune-stuff/pull/2
https://github.com/renemilk/dune-stuff/pull/1
Open for opinions.

**Comment by renemilk** [comment]
Project seems dead https://github.com/linthubot/linthub-demo/issues/13 , imo that's a no then.

**Comment by ftalbrecht** [comment]
agreed
