### ISSUE TITLE
Stop using external ALUGrid in favor of dune-alugrid?

### ISSUE THREAD

**Issue by renemilk** [wwu-numerik/dune-stuff#95]
I see no reason not to, besides transition is work. On the plus side It'll avoid link errors like https://travis-ci.org/wwu-numerik/dune-stuff/jobs/96946956#L4946 and be one less external lib to build.

**Comment by ftalbrecht** [comment]
I agree mostly! However, dune-alugrid behaves differently from alugrid. Using the same ctors yields other grids, for instance. So I am pro transitioning but would like to have some time to make sure we can keep all the functionality we require. Feel free to assign this to me.

**Comment by renemilk** [comment]
There's a compelling reason not to wait with this though: https://gitlab.dune-project.org/core/dune-grid/merge_requests/1
the support is already removed from dune-grid.

**Comment by renemilk** [comment]
This issue was moved to dune-community/dune-xt-grid#2
