### ISSUE TITLE
incorporate changes from dune-gdt refactor branch

### ISSUE THREAD

**Issue by ftalbrecht** [wwu-numerik/dune-stuff#98]
This is required for the next/last release. These changes also have to find their way into dune-xt afterwards...

**Comment by ftalbrecht** [comment]
There is the https://github.com/ftalbrecht/dune-stuff/tree/phd-schindler branch which collects all publications. After applying clang-format there, we need to merge it into the `RS2016` branch (where clang-format has to be applied as well). The resulting branch then has to be merged with the dune-gdt refactor branch (after applying clang-format there) and back onto master. Have fun...

**Comment by renemilk** [comment]
Happened in https://github.com/wwu-numerik/dune-stuff/tree/refactor_operators_and_products_in_dune_gdt_with_cmake_fixed_and_master_merged

IIRC we decided to not have this as the new master.

**Comment by renemilk** [comment]
Closing all remaining dune-stuff tickets. Please see https://github.com/dune-community and the dune-xt modules there.
